version: '3'

services:
    db:
        image: mysql
        port:
            -'3306:3306'
        environment:
            MYSQL_DATABASE: 'OllinCafe'
            MYSQL_USER: 'OllinAdmin'
            MYSQL_PASSWORD: '0120200920'
            MYSQL_ROOT_PASSWORD: 'Ltk99701299'
    web:
        build:
            command: python manage.py runserver 0.0.0.0:8000
            volumes:
                -.:/OllinCafe
            port:
                -"8000:8000"
            depends_on:
            -db 